### ISSUE TITLE
TODO/FIXME Count 1

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/bedrock-quasar#9]
- [ ] TODO: consider monkey-patching CSSStyleDeclaration.prototype.setProperty
       Commit: (c3fc1ab) Add monkey-patch for CSSStyleDeclaration.prototype.setProperty.
       File:  [index.js:62](https://github.com/digitalbazaar/bedrock-quasar/blob/master/index.js#L62)
       Dave Longley commented 2 years ago

**Comment by dlongley** [comment]
Addressed by #11.
